js/fullcalendar.js.php

j'ai une erreur js en 5.0 (que je n'ai pas en 4.0 étrangement) mais il manque une }

Fix TK6028 - error js

---

admin/fullcalendar_setup.php
core/modules/modfullcalendar.class.php
js/fullcalendar.js.php
langs/fr_FR/fullcalendar.lang
script/interface.php

- Le clic sur un event ouvre la popin d'édition (comme pour l'ajout)
- Le lien n'est donc plus sur l'event entier mais sur le titre
- New con pour saisir l'état d'avancement

New comportment click

---

js/fullcalendar.js.php
script/interface.php

1/ modal fuck ckeditor add link
2/ multiselectarray disabled js inclusion
3/ add inclusion hover
4/ set manually element into to conserv good order for owner

New multiselect user

---

js/fullcalendar.js.php

- bordel à comprendre, mais c'est juste un extract de la déclaration des boutons pour pouvoir rajouter le bouton clone que si nécessaire

NEW clone event

---

ChangeLog.md
core/modules/modfullcalendar.class.php
script/interface.php

V13 compatibility after renaming contactid properties into contact_id

FIX/V13 Compatibility

---

ChangeLog.md
core/modules/modfullcalendar.class.php
langs/fr_FR/fullcalendar.lang
script/interface.php
task.php

l doit être possible de modifier les champs suivants de la tâche depuis la vue planning. Se référer à la spécification pour les détails de mise en oeuvre.
Libellé de la tâche
Date de début
Date de fin
Charge de travail prévue
Description
Progression déclarée
Poste de charge

New : Edition taches ordonnacement

---

ChangeLog.md
core/modules/modfullcalendar.class.php

- editor_name = 'ATM Consulting'
- editor_url = "https://www.atm-consulting.fr"
- family = 'ATM Consulting – Autres'

FIX : Compatibility V14 - Modify descriptor informations

---

ChangeLog.md
core/modules/modfullcalendar.class.php
js/fullcalendar.js.php

Compatibility V13 - Add token renowal

FIX : add token renowal

---

ChangeLog.md
core/modules/modfullcalendar.class.php
js/fullcalendar.js.php

Compatibility V13 - changement of $user->societe_id => $user->socid

FIX : societe_id became socid

---

ChangeLog.md
core/modules/modfullcalendar.class.php
js/fullcalendar.js.php

Bug affichage fullcalendar après activation conf reminders module agenda

FIX : Conf reminders full calendar

---

ChangeLog.md
core/modules/modfullcalendar.class.php
js/fullcalendar.js.php

PR d'origine : https://github.com/ATM-Consulting/dolibarr_module_fullcalendar/pull/64

PULLUP Main - FIX : conf reminders full calendar

---

ChangeLog.md
admin/fullcalendar_about.php
class/techatm.class.php
core/modules/modfullcalendar.class.php

NEW : Add about page with techAtm class

NEW : Add about page with techAtm class

---

ChangeLog.md
core/modules/modfullcalendar.class.php
js/fullcalendar.js.php
task.php

Bug affichage de la couleur du texte (horaires, description, liens) en fonction de la couleur de fond des évènements (couleur clair ou foncée)

Fix : Events colors according to event's background color

---

ChangeLog.md
README
js/fullcalendar.js.php
task.php

PR d'origine : https://github.com/ATM-Consulting/dolibarr_module_fullcalendar/pull/71

PULLUP_Main : Fix colors

---

ChangeLog.md
README
admin/fullcalendar_setup.php
admin/fullcalendar_task_setup.php

https://github.com/ATM-Consulting/dolibarr_module_fullcalendar/pull/67

NUM 1 :PULLUP : FIX Compat V16 - New token

---

ChangeLog.md
core/modules/modfullcalendar.class.php
js/fullcalendar.js.php
task.php

FIX : Compat V16 - Ajout de token

FIX : Compat V16 - Ajout de token

---

ChangeLog.md
js/fullcalendar.js.php
task.php

voir https://github.com/ATM-Consulting/dolibarr_module_fullcalendar/pull/73

PULLUP [main] | FIX : Compatibilité V16 - Token

---

ChangeLog.md
core/modules/modfullcalendar.class.php

FIX : position du premier menu pour eviter l'erreur bloquante menu déjà existant

fix first menu position

---

ChangeLog.md
core/modules/modfullcalendar.class.php

FIX : position du premier menu pour eviter l'erreur bloquante menu déjà existant

PULL UP : Fix existing menu at load module

---

ChangeLog.md
core/modules/modfullcalendar.class.php
js/fullcalendar.js.php

#FIX fullcalendar was not reacting to standard viewmode

fix fullcalendar was not reacting to standard viewmode

---

ChangeLog.md
core/modules/modfullcalendar.class.php
js/fullcalendar.js.php

fullcalendar was not reacting to standard viewmode

PULL UP : fix fullcalendar was not reacting to standard viewmode

---

ChangeLog.md
core/modules/modfullcalendar.class.php
script/interface.php

See : https://github.com/ATM-Consulting/dolibarr_module_fullcalendar/pull/81

[PULLUP] FIX | DA023055 : cas non applicable :

---

ChangeLog.md
core/modules/modfullcalendar.class.php
js/fullcalendar.js.php

DA024569 - Suppression des boutons standards en double avec full calendar + déplacement du bouton de recherche a coté des filtres

2.5 FIX Suppression des boutons standards en double avec full calendar

---

ChangeLog.md
js/fullcalendar.js.php

DA024569 - Suppression des boutons standards en double avec full calendar + déplacement du bouton de recherche a coté des filtres

pullup 2.5 FIX Suppression des boutons standards en double avec full calendar 

---

ChangeLog.md
js/fullcalendar.js.php

2.6 fix hide useless filter DA024569

2.6 fix hide useless filter

---

ChangeLog.md
core/modules/modfullcalendar.class.php
js/fullcalendar.js.php
script/interface.php

https://doliboard.atm-consulting.fr/ticket/card.php?id=4822&save_lastsearch_values=1

FIX - Checkbox external calendar

---

ChangeLog.md
core/modules/modfullcalendar.class.php
js/fullcalendar.js.php
script/interface.php

PULL UP de cette PR : 
https://github.com/ATM-Consulting/dolibarr_module_fullcalendar/pull/94

PULLUP - FIX - Checkbox external calendar

---

ChangeLog.md
config.default.php
core/modules/modfullcalendar.class.php

PULL UP de cette PR : https://github.com/ATM-Consulting/dolibarr_module_fullcalendar/pull/100

PULLUP -  FIX - Warnings sur activation

---

ChangeLog.md
class/actions_fullcalendar.class.php
core/modules/modfullcalendar.class.php
js/fullcalendar.js.php

Pas de fullcalendar sur la vue agenda

FIX : DA024854 - Compat v19

---

ChangeLog.md
class/actions_fullcalendar.class.php
core/modules/modfullcalendar.class.php
js/fullcalendar.js.php

Voir : https://github.com/ATM-Consulting/dolibarr_module_fullcalendar/pull/102

PULLUP [main] | FIX : DA024854 - Compat v19 

---

ChangeLog.md
core/modules/modfullcalendar.class.php
js/fullcalendar.js.php
script/interface.php

Ajout de la gestion des congés sur full calendar

DA024563 -FIX - Checkbox congés 

---

ChangeLog.md
core/modules/modfullcalendar.class.php
script/interface.php

- Suppression du fetch de chaque évenement apres la requête de sélection

FIX :  Suppression du fetch de chaque évenement apres la requête de sélection - da025157

---

ChangeLog.md
core/modules/modfullcalendar.class.php
script/interface.php

- Affichage de l'évènement sur le bon fuseau horaire 
- Affichage de la complétion des événements
- Affichage des couleurs des évènements en fonction de la couleur utilisateur
- Assignation du bon propriétaire lors de la création d'un évenement

FIX 2.7 da025157 and da025414

---

ChangeLog.md
core/modules/modfullcalendar.class.php
js/fullcalendar.js.php
script/interface.php

Lors de la modification d'un événement, certains des champs étaient vides & certains événements n'étaient même pas éditables

FIX - SP126 - DA025444 - Bugs lors de la modification d'événements fullCalendar

---

ChangeLog.md
core/modules/modfullcalendar.class.php
js/fullcalendar.js.php
script/interface.php

[PR](https://github.com/ATM-Consulting/dolibarr_module_fullcalendar/pull/131)

PULLUP - FIX - SP126 - DA025444 - Bugs lors de la modification d'événements fullCalendar

---

ChangeLog.md
core/modules/modfullcalendar.class.php
script/interface.php

PULLUP de [CETTE PR](https://github.com/ATM-Consulting/dolibarr_module_fullcalendar/pull/135)

PULLUP - FIX : DA025956 - FIX bug php 8.2

---

ChangeLog.md
core/modules/modfullcalendar.class.php
js/fullcalendar.js.php
script/interface.php

Remplissage de l'input société qui était vidé alors que l'enregistrement fonctionnait

FIX - DA025956 - Remplissage info manquante popin

---

ChangeLog.md
core/modules/modfullcalendar.class.php
js/fullcalendar.js.php
script/interface.php

PULLUP de [CETTE PR](https://github.com/ATM-Consulting/dolibarr_module_fullcalendar/pull/137)

PULLUP - FIX - DA025956 - Remplissage info manquante popin

---

ChangeLog.md
core/modules/modfullcalendar.class.php
script/interface.php

annulation du fix DA025956 qui rend impossible  le rendu des events congés dans le calendrier

affichage des congés dans l'agenda 

---

ChangeLog.md
core/modules/modfullcalendar.class.php
js/fullcalendar.js.php

Ajout d'un mode sur un dol_escape_js pour éviter des erreurs dans la console

FIX - SUPPORT - DA02711 - Ajout d'un mode sur un dol_escape_js pour eviter des erreurs dans la console
